default:
  app:
    name: {{ asyncapi.info().title() }}
    version: {{ asyncapi.info().version() }}
{% if asyncapi.server(params.server).protocol() === "ws" %}
  ws:
    port: {{ asyncapi.server(params.server).url() | port(80) }}
    path: /ws
    topicSeparator: '__'
{% endif %}
{%- if asyncapi.server(params.server).protocol() !== "ws" %}
  broker:
{%- endif %}
{%- if asyncapi.server(params.server).protocol() === "amqp" %}
    amqp:
      exchange:
      username:
      password:
      host: {{ asyncapi.server(params.server).url() | host }}
      port:
      topics: {{ asyncapi | channelNamesWithPublish | toAmqpTopic | dump | safe }}
      queue: {{ asyncapi.info().title() | queueName(asyncapi.info().version()) }}
      queueOptions:
        exclusive: false
        durable: true
        autoDelete: true
{%- endif %}
{%- if asyncapi.server(params.server).protocol() === "mqtt" %}
    mqtt:
      url: mqtt://{{ asyncapi.server(params.server).url() | stripProtocol }}
      topics: {{ asyncapi | channelNamesWithPublish | toMqttTopic | dump | safe }}
      qos:
      protocol: mqtt
      retain:
      subscribe: true
{%- endif %}
{%- if asyncapi.server(params.server).protocol() === "kafka" %}
    kafka:
      clientId: {{ asyncapi.info().title() | camelCase }}
      brokers: ["{{ asyncapi.server(params.server).url() | host }}"]
      consumerOptions:
        groupId: 'replace-me'
      topics: {{ asyncapi | channelNamesWithPublish | toKafkaTopic | dump | safe }}
      topicSeparator: '__'
{%- endif %}

development:

test:

staging:

production:

